stages:
  - build
  - test
  - clean

variables: &global-variables
  CONDA_PATH: /scratch/olly/gitlab_wd/test_env

linux-build:
  stage: build
  tags:
    - linux
  script:
    - "mkdir -p $CONDA_PATH"
    - "conda env create -f environment.yml -p $CONDA_PATH"
    - conda activate $CONDA_PATH
    - "module load cuda/10.1"
    - pip install pycuda
    - bash make_script.sh
    - conda deactivate

linux-test:
  stage: test
  tags:
    - linux
  script:
    - module load cuda/10.1
    - conda activate $CONDA_PATH
    - bash make_script.sh
    - "python -m pytest tests/"

linux-clean:
  stage: clean
  tags:
    - linux
  script:
    - conda deactivate
    - "conda remove -p $CONDA_PATH --all"
  when: always
