language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux
  
sudo: false
  
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda install --yes --file requirements.txt
    
install:
  - echo "SUCCESS" #- python setup.py build_ext --inplace
  
script:
  - pytest
