language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux
  
sudo: false
  
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
    
install:
  - cat requirements.txt | grep -v pycuda | xargs pip install
  - conda install -c lukepfister pycuda
  - conda install pytest

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  
script:
  - pytest tests/
