name: survos2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - h5py
  - cython
  - pytools
  - pytest
  - pywget
  - hug
  - pyyaml
  - mrcfile
  - dask
  - matplotlib
  - scikit-image
  - tensorly

