proj: hunt
preprocessing: {}
random_seed_main: 32
marker_size: 10
refine_lambda: 1.0
resample_amt: 0.5
save_output_files: false
mscale: 1.0
plot_all: false
roi_crop:
- 0
- 2500
- 0
- 2500
- 0
- 2500
torch_models_fullpath: ../experiments
current_annotation: 001_level
filter_cfg:
  superregions1:
    plugin: superregions
    feature: slic
    params:
      slic_feat_idx: -1
      compactness: 20
      postprocess: false
      sp_shape:
      - 18
      - 18
      - 18
  filter1:
    plugin: features
    feature: gaussian
    params:
      sigma: 2
  filter2:
    plugin: features
    feature: gaussian
    params:
      sigma: 2
  filter3:
    plugin: features
    feature: tvdenoising3d
    params:
      lamda: 3.7
  filter4:
    plugin: features
    feature: simple_laplacian
    params:
      sigma: 2.1
  filter5:
    plugin: features
    feature: gradient
    params:
      sigma: 3
pipeline:
  calculate_features: true
  calculate_supervoxels: true
  load_pretrained_classifier: true
  load_annotation: false
  predict_params:
    clf: ensemble
    type: rf
    n_estimators: 10
    proj: false
    max_depth: 20
    n_jobs: 1
  mask_params:
    mask_radius: 10
