title: 'SuRVoS2: Super-Region Volume Segmentation Workbench'

api:
  plugins:
    - workspace
    - annotations
    - features
    - regions
    - render
    - pipelines
    - entitys
computing:
  chunks: true
  chunk_size: 64     # 1 Gb
  chunk_padding : 8

logging:
  level: info

environments:
  ###########################################
  # Set with SURVOS_ENV environment variable
  # Will overwrite existing configs
  ###########################################
  test: # SURVOS_ENV=test
    api:
      renderer: mpl  

    computing:
      chunks: false      # Automatic chunking
      chunk_size: 10   # in MB
      chunk_size_sparse: 10

    model:
      chroot: temp       # will create a temporary directory

    logging:
      file: /tmp/survos.log
      level: debug
