model:
  chroot: /dls/science/groups/das/SuRVoS/s2/data
  dbtype: yaml
api:
  host: 127.0.0.1
  plugins:
  - workspace
  - render
  - server
  - features
  - superregions
  - annotations
  - pipelines
  - objects
  - analyzer
  - roi
  - export
  port: 8123
  renderer: mpl
computing:
  chunk_padding: 8
  chunk_size: 10
  chunk_size_sparse: 10
  chunks: true
  scale: false
  stretch: false
filters:
  filter1:
    feature: gaussian
    params:
      sigma: 2
    plugin: features
  filter2:
    feature: gaussian
    params:
      sigma: 2
    plugin: features
  filter3:
    feature: tvdenoising3d
    params:
      lamda: 3.7
    plugin: features
  filter4:
    feature: laplacian
    params:
      kernel_size: 3
    plugin: features
  filter5:
    feature: gradient
    params:
      sigma: 3
    plugin: features
  superregions1:
    feature: slic
    params:
      compactness: 20
      postprocess: false
      slic_feat_idx: -1
      sp_shape:
      - 18
      - 18
      - 18
    plugin: superregions
logging:
  file: ''
  file_format: '%(asctime)s - | %(levelname)8s | %(message)s'
  level: debug
  std: true
  std_format: '%(levelname)8s | %(message)s'
pipeline:
  calculate_features: true
  calculate_supervoxels: true
  load_annotation: false
  load_pretrained_classifier: true
  mask_params:
    mask_radius: 10
  predict_params:
    clf: Ensemble
    max_depth: 20
    n_estimators: 10
    n_jobs: 1
    proj: rproj
    type: rf
qtui:
  maximized: false
  menuKey: \
slic: skimage
title: 'SuRVoS2: Super-Region Volume Segmentation Workbench'
volume_mode: volume
