name: Github CI/CD
on:
  push:
    branches: [ main ]
env:
      LINUX_CONDA_PATH: /test_env
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        #$CONDA/bin/conda env update --file environment.yml --name base
        pip install --no-cache-dir -r req.txt



